### PR TITLE
Custom fare calculators

### PR DESCRIPTION
**Pull request by mattwigway**
This adds support for using built-in R5 fare calculators. If a fare system has a "type" field, it is treated as an R5 fare calculator.

I've tested this with the Boston fare calculator. @dhersz or @rafapereirabr, can you confirm it still works with the R5R calculator? More broadly, do we have an automated test suite? The Boston fare calculator gives this Pareto result (from Norwood Central to Copley), which matches the one in Conway and Stewart (2019):

image

And this accessible area for $3/$15:

image

I've also removed the warnings about frequencies from the fare calculators, as McRAPTOR does actually work with frequencies when working with fares (not sure when creating detailed itineraries).

I've also made some changes to the Java build process. The Java code is now built with Gradle, and Github Actions builds a new jar and commits it whenever the Java code changes. I'm not a big fan of checking binaries into repositories, maybe in future we could build the JAR as part of the CRAN package build, or host the r5r jar on Github Releases the same way R5 itself is. I use the JRI.jar that is shipped with rJava rather than one checked into the repository.

### CODE REVIEW

**Comment by rafapereirabr** [comment]
Thanks, Matt. On a quick look, this looks really promising. I'll check with @mvpsaraiva if he can have a closer look at the PR. In the meantime, would you have a sample data we could use to test the modifications ?

**Comment by mvpsaraiva** [comment]
Thanks a lot, Matt. That's a great contribution and it looks very cool! I'll take a closer look in the following days, but it seems our tests are already passing. We only have tests in R because they end testing the java code as well. I didn't write specific tests in Java because they would be redundant. 
Thanks for the build system as well, that will save a lot of time. I don't like checking binaries into repositories as well, but r5r's "little jar" (as we call it) is just around 100k so I left to deal with it later (however, there's nothing more permanent than a temporary solution, so the binary is still there lol). I think the JRI.jar checked in the repository may be a mistake, I'll take a look at that too.

**Comment by rafapereirabr** [comment]
Hi @mattwigway ,would you have a sample data (GTFS and fare rules) we could use to test the modifications you proposed?

**Comment by mattwigway** [comment]
@ansoncfit what city should we use for the comparison? Boston/NYC/Chicago?

**Comment by rafapereirabr** [comment]
Hi guys. Whichever city we choose, we will need to crop a relativelly small area around the city center to include it as a sample data for reproducible example embarked with the r5r package.  Like we do for Sao Paulo and Porto Alegrege.

**Comment by mattwigway** [comment]
Do we need the paper to be a reprex within the r5r package? In the US
anyways the fare systems are most interesting when you have local and
regional services interacting.

**Comment by rafapereirabr** [comment]
Hi @mattwigway , could you send us a sample data (GTFS and fare rules) of Chicago so we could test the modifications you proposed?

**Comment by mattwigway** [comment]
I haven't done any work with Chicago, but I think @ansoncfit has.

**Comment by rafapereirabr** [comment]
@mattwigway , the sample data for NYC would work as well. For now, we just need some data to test the changed you pushed in this Pull Request

**Comment by rafapereirabr** [comment]
thanks, Matt. We can work with a sample data for Boston for the purposes of testing your PR

**Comment by ansoncfit** [comment]
Hey all,

Sorry, I just realized I missed some mentions here. I'll see what I can pull together for Chicago in the next two weeks.

**Pull request merged**
