### PR TITLE
update JDK install instructions, fixes #366

### LINKED ISSUE #366: Simplify JDK download instructions
The download instructions on https://ipeagit.github.io/r5r/ for the JDK are currently somewhat confusing to someone not well versed in Java. We currently link to two pages for getting the JDK:

- https://jdk.java.net/java-se-ri/21 and
- https://docs.oracle.com/en/java/javase/21/install/index.html#Java-Platform%2C-Standard-Edition

neither of which actually provide a JDK download anymore. I think we should pick one of the three open source JDK implementations, and just link to that. Anyone who has a preference for what JDK to use is going to ignore these instructions anyways. The three I'm familiar with are:

- Eclipse Temurin: https://adoptium.net/
- Amazon Corretto: https://aws.amazon.com/corretto
- Oracle OpenJDK: https://jdk.java.net/21/

I am usually running either Temurin or Corretto on my machines, I haven't touched anything from Oracle in years. Conveyal uses Corretto to run the R5 test suite.

### PR DESCRIPTION
**Pull request by mattwigway**
Fix #366, make instructions for installing the JDK more clear and straightforward.

### CODE REVIEW

**Comment by rafapereirabr** [comment]
thanks!

**Comment by mattwigway** [comment]
This should not have triggered a JAR rebuild, hmm.

**Comment by mattwigway** [comment]
The JAR rebuild appears to be configured correctly: https://github.com/ipeaGIT/r5r/blob/master/.github/workflows/java-r5rcore-build.yaml#L6

It also seems like it has not run on commits that did not make java changes in the past, so maybe a transient Github issue? Anyways, I just force-pushed back to the previous commit, so this should be able to be merged now.

**Comment by rafapereirabr** [comment]
thanks, Matt! Merging pr now.

**Pull request merged**
